services:
  server:
    build:
      context: ./server
    container_name: lower-that-server
    environment:
      # Required
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Optional, defaults to false here to avoid requiring TV envs
      TV_CONTROL_ENABLED: ${TV_CONTROL_ENABLED:-false}
      SAMSUNG_TV_IP_ADDRESS: ${SAMSUNG_TV_IP_ADDRESS:-}
      SAMSUNG_TV_MAC_ADDRESS: ${SAMSUNG_TV_MAC_ADDRESS:-}
      PORT: 3000

  web:
    build:
      context: ./web
    container_name: lower-that-web
    environment:
      # Point Vite dev proxy at the server service
      VITE_API_PROXY_TARGET: http://server:3000
    ports:
      - '5173:5173'
    depends_on:
      - server

